export const certificates = [
  {
    title: "Frontend Development with React",
    issuer: "Packt",
    date: "January 17, 2025",
    platform: "Coursera",
    link: "https://coursera.org/verify/WBL4STTGGAHF",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "Introduction to Java",
    issuer: "LearnQuest",
    date: "January 17, 2025",
    platform: "Coursera",
    link: "https://coursera.org/verify/VE9EK49U0I9P",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "Introduction to Object-Oriented Programming with Java",
    issuer: "LearnQuest",
    date: "January 17, 2025",
    platform: "Coursera",
    link: "https://coursera.org/verify/WNAAIZKORPCZ",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "Backend Development and API Creation",
    issuer: "Packt",
    date: "January 17, 2025",
    platform: "Coursera",
    link: "https://coursera.org/verify/PEK73T3CJN4S",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "Spring MVC, Spring Boot and Rest Controllers",
    issuer: "LearnQuest",
    date: "January 20, 2025",
    platform: "Coursera",
    link: "https://coursera.org/verify/CR8U8G6GH1C1",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "AWS Academy Introduction to Cloud - Semester 1",
    issuer: "AWS Academy",
    date: "September 13, 2024",
    platform: "Credly",
    link: "https://www.credly.com/go/1ynqu7G",
    image: "/images/Certificates/AWSAcademy.png",
  },
  {
    title: "AWS Academy Introduction to Cloud - Semester 2",
    issuer: "AWS Academy",
    date: "September 13, 2024",
    platform: "Credly",
    link: "https://www.credly.com/go/W0KgQrB6",
    image: "/images/Certificates/AWSAcademy.png",
  },
  {
    title: "AWS Cloud Practitioner Essentials",
    issuer: "Amazon Web Services",
    date: "January 20, 2025",
    platform: "Coursera",
    link: "https://coursera.org/verify/WE4P9K17QPS8",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "Cloud Computing Basics (Cloud 101)",
    issuer: "LearnQuest",
    date: "September 16, 2022",
    platform: "Coursera",
    link: "https://coursera.org/verify/FX37TXR7TEXT",
    image: "/images/Certificates/Coursera.png",
  },
  {
    title: "Blockchain 101",
    issuer: "Infosys Springboard",
    date: "February 17, 2024",
    platform: "OnWingspan",
    link: "https://verify.onwingspan.com",
    image: "/images/certificates/Infosys.png",
  },
  {
    title: "Blockchain in Depth",
    issuer: "Infosys Springboard",
    date: "March 2, 2024",
    platform: "OnWingspan",
    link: "https://verify.onwingspan.co",
    image: "/images/certificates/Infosys.png",
  },
];
